# 文件名: 03_positional_encoding.yaml
project_name: "cs336-exp3-posemb"


common:
  data:
    train_path: "output/owt_train.npy"
    val_path: "output/owt_valid.npy"
  training:
    device: "cuda"
    batch_size: 64
    max_iters: 25000
    learning_rate: 3e-4
    min_lr: 3e-5
    warmup_iters: 1000
    weight_decay: 0.1
    beta1: 0.9
    beta2: 0.95
    eps: 1e-8
    grad_clip: 1.0
  checkpoint:
    out_dir_base: "checkpoints/exp3"
    save_interval: 2000

experiments:
  - run_name: "Pos-RoPE"
    model: &base_model
      vocab_size: 10000
      context_length: 256
      d_model: 256
      num_layers: 4
      num_heads: 4
      d_ff: 1024
      rope_theta: 10000.0
      norm_location: "post"
      norm_type: "layernorm"
      ffn_type: "relu"
      weight_tying: true
      dropout: 0.1
      pos_emb_type: "rope"       # <--- 变量

  - run_name: "Pos-NoPE"
    model:
      <<: *base_model
      pos_emb_type: "none"       # <--- 变量

  - run_name: "Pos-Sinusoidal"
    model:
      <<: *base_model
      pos_emb_type: "sinusoidal" # <--- 变量

  - run_name: "Pos-Learned"
    model:
      <<: *base_model
      pos_emb_type: "learned"    # <--- 变量